name: "[FR] Feedback ticket"
description: Merci de votre retour construit et bienveillant !
title: "[FEEDBACK][FR] <Date> <player>"
labels: Feedback
assignees: Fr-Dae
body:
  - type: textarea
    attributes:
      label: Système d'exploitation
      description: Indiquez votre système d'exploitation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Version du tutoriel
      description: Indiquez la version du tutoriel avec laquelle vous jouez
      placeholder: |
        1.1.1 "standalone"
      render: markdown
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Nouveau sur Unitystation ?
      description: Êtes-vous un nouveau joueur d'UnityStation ?
      options:
        - label: Je suis nouveau sur UnityStation
  - type: checkboxes
    attributes:
      label: Nouveau sur SS13 ?
      description: Avez-vous déjà joué à SS13 ?
      options:
        - label: Je suis nouveau sur SS13
  - type: textarea
    attributes:
      label: A propos du tutoriel
      description: Feedback concernant le tutoriel du jeu uniquement
      value: |
        Ce que j'ai apprécié: 
          -
          -
          -
        Ce que je n'ai PAS apprécié: 
          -
          -
          -
        Ce que je n'ai pas compris: 
          -
          -
          -
      render: markdown
    validations: 
      required: true
  - type: textarea
    attributes:
      label: A propos du reste du jeu Unitystation
      description: |
        Exemples de points à aborder: 
          - Moteur du jeu
          - Durée du tutoriel
          - Complexité
          - Musique
          - Ambiance et effet sonore
          - Interface et menu
          - Prise en main et Intuitivité 
          - Libre arbitre
          - User friendly
      value: |
        Ce que j'ai apprécié: 
          -
          -
          -
        Ce que je n'ai PAS apprécié: 
          -
          -
          -
        Ce que je n'ai pas compris: 
          -
          -
          -
      render: markdown
    validations: 
      required: false
  - type: textarea
    attributes:
      label: Autres commentaires
      description: Quelque chose à ajouter ?
    validations:
      required: false

